server:
  port: 8080
spring:
  application:
    name: pedido
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidodb
    username: juanchire
    password: 123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
